default: &default
  adapter: postgresql
  encoding: unicode
  username: ideadash
  password: ideadash
  pool: 10

development:
  <<: *default
  database: ideadash_development

test:
  <<: *default
  database: ideadash_test

production:
  <<: *default
  database: <%= ENV['IDEADASH_DATABASE'] %>
  username: ideadash
  password: <%= ENV['IDEADASH_DATABASE_PASSWORD'] %>
