test: &default

  client_id: <%= ENV['PAYPAL_CLIENT_ID'] %>
  client_secret: <%= ENV['PAYPAL_CLIENT_SECRET'] %>

  mode: sandbox

development:
  <<: *default

production:
  <<: *default
  mode: <%= ENV['PAYPAL_MODE'] || 'live' %>
