test: &default

  client_id: <%= ENV['PAYPAL_CLIENT_ID'] %>
  client_secret: <%= ENV['PAYPAL_CLIENT_SECRET'] %>

  mode: sandbox

  # Credentials for Classic APIs
#  app_id: <%= ENV['PAYPAL_APP_ID'] %>
#  username: <%= ENV['PAYPAL_USERNAME'] %>
#  password: <%= ENV['PAYPAL_PASSWORD'] %>
#  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
#  sandbox_email_address: <%= ENV['PAYPAL_SANDBOX_EMAIL_ADDRESS'] %>

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
